### ISSUE TITLE
Common Dialogs, right click menu broken on Windows 10

### ISSUE THREAD

**Issue by joongtang** [RRUZ/Delphi-IDE-Colorizer#10]
![opendialogissueinw10](https://cloud.githubusercontent.com/assets/6409795/11424959/ab3a7918-9494-11e5-83a0-be1597751a02.png)

Invoke a common dialog (TOpenDialog, TFileOpenDialog), right click inside the dialog, the menu shows garbled characters.

This issue is similar to [RSP-11814](http://edn.embarcadero.com/article/44619), but this issue is slightly different from RSP-11814. English text is normal, non english text is broken.

**Comment by RRUZ** [comment]
I just fixed the issue. Try the new version 0.8.2.5

**Comment by joongtang** [comment]
Thanks!! ^^
