### ISSUE TITLE
setup_DIC.exe flagged as infected by Symantec Endpoint Protection.

### ISSUE THREAD

**Issue by radcuman69** [RRUZ/Delphi-IDE-Colorizer#11]
My antivirus kicks the downloaded installation program as being infected with a virus.  Has anyone else reported any issues like that? I am using it on XE7 and lower and don't recall a problem.  However, when I try to download the latest from github symantec endpoint flags it has being infected with WS.Reputation.1.  Can you check the download mirrors to make sure it is clean?

**Comment by RRUZ** [comment]
This is a false positive, you can upload the file to *VirusTotal* and check that your self.

Anyway this is the Scan report  for the installer.

https://www.virustotal.com/en/file/964187a13d5e45df2e61a76da3de2326a71627241c4c890512f5d1835289b09e/analysis/1449634155/

**Comment by radcuman69** [comment]
Thanks for checking.  I added an exception after I downloaded the latest fast-reports installer and it was tagged with the same thing.
