### ISSUE TITLE
Delphi IDE Colorizer spoils DrawEdge function

### ISSUE THREAD

**Issue by errorcalc** [RRUZ/Delphi-IDE-Colorizer#14]
Is you activte Delphi IDE Colorizer then function Windows.DrawEdge stops working as expected.
The function does not draw a egde correctly, it begins to fill the entire area with the background color.
This can be seen on some components, ex: TJvColorTrackBar in JEDI project:
```
  if BorderStyle = bsSingle then
    DrawEdge(FBmpImage.Canvas.Handle, R, EDGE_SUNKEN, BF_TOP or BF_RIGHT or BF_BOTTOM or BF_LEFT);
```
---

**Steps:**
1. Install JEDI VCL
2. Add TJvColorTrackBar to form
**EXP:** draw edge
**ACT:** fills the entire rectangle of background theme(Delphi IDE Colorizer) color
(If you run the application you will get expected result)

**Comment by RRUZ** [comment]
Hi, Unfortunatly there is not workaround for this. I updated the [wiki](https://github.com/RRUZ/Delphi-IDE-Colorizer/wiki) of the project with this info. **However this doesn't affect to the binaries generated by the IDE.**
