### ISSUE TITLE
Anyway to change the font color of the Tool Palette?

### ISSUE THREAD

**Issue by 3ndl3ss-l00p** [RRUZ/Delphi-IDE-Colorizer#15]
![2016-03-06_232922](https://cloud.githubusercontent.com/assets/16831365/13555161/e8fae6c6-e3f3-11e5-9399-6225e51550fe.png)
This is in "Default Layout" for D10. I need to change the font to white color (or any color). Thanks.

**Comment by RRUZ** [comment]
Hello, This was a bug. Please try the version 0.8.7.1

**Comment by 3ndl3ss-l00p** [comment]
Confirmed fix for me on ver. 0.8.7.1

Thanks!
