### ISSUE TITLE
RAD Studio Berlin

### ISSUE THREAD

**Issue by fschenckel** [RRUZ/Delphi-IDE-Colorizer#18]
Hello,

I've checked in the code, but compatibility with Berlin 10.1 seems to be problematic because of the change of not getting access to the private symbols anymore.
Does someone have a solution for this ?

**Comment by RRUZ** [comment]
Hi, you must be patient with this, because the class helper limitation introduced in Berlin, causes several issues to compile the code, and fix all these will take some time.

Regards
Rodrigo.

**Comment by fschenckel** [comment]
Hello,

Thanks for your answer !!
I began to check the code and applied the trick I have seen in the JVCL (Create a dummy class with similar structure) to get the correct offset.
It compiles but it doesn’t work correctly so far, mainly because of the hook on the procedure / functions.

I know it is a bad fix for this and will not stand over several version, but it was just a try.
Right at the moment I don’t have time to spend on this project, but I will have a few hours in the next days. If you’re interested I can send you the changes…


Regards


Frédéric


De : Rodrigo Ruz [mailto:notifications@github.com]
Envoyé : mardi 17 mai 2016 17:43
À : RRUZ/Delphi-IDE-Colorizer
Cc : Frédéric SCHENCKEL; Author
Objet : Re: [RRUZ/Delphi-IDE-Colorizer] RAD Studio Berlin (#18)


Hi, you must be patient with this, because the class helper limitation introduced in Berlin, causes several issues to compile the code, and fix all these will take some time.

Regards
Rodrigo.

**Comment by RRUZ** [comment]
Hello Frédéric,  any help is appreciated on these days ;), please feel free to post your changes using a pull request.

**Comment by RRUZ** [comment]
Hello Frédéric, I just added support for RAD Studio 10.1 Berlin  to the plugin, try the version 0.8.7.1

**Comment by fschenckel** [comment]
Hello Rodrigo,

Cool yes it works !!
I didn't tought about getting directly the address for the .bpl. Well done !
