### ISSUE TITLE
RAD Studio for Windows has stopped working 

### ISSUE THREAD

**Issue by halyson** [RRUZ/Delphi-IDE-Colorizer#2]
After installing Delphi XE2 does not open , the message , ” Embarcadero RAD Studio for Windows has stopped working .”
I had to uninstall IDEColorizer

![2015-07-14_17h00_08](https://cloud.githubusercontent.com/assets/3737523/8700932/38c329b6-2ae5-11e5-9a92-4c61b54851e3.jpg)

**Comment by RRUZ** [comment]
Thanks for report this. Can you please attach the windows log error associated to this exception?

**Comment by halyson** [comment]
My system is PT-BR
====================
Nome de aplicativo com falha: bds.exe, versão: 16.0.4429.46931, carimbo de hora: 0x4f3db018
Nome do módulo de falhas: rtl160.bpl, versão: 16.0.4429.46931, carimbo de hora: 0x4f3db5bf
Código de exceção: 0xc0000005
Deslocamento com falha: 0x0003b86f
Identificação do processo com falha: 0x15ec
Hora de início do aplicativo com falha: 0x01d0be6f979e3ae5
Caminho do aplicativo com falha: C:\Program Files (x86)\Embarcadero\RAD Studio\9.0\bin\bds.exe
FCaminho do módulo de falhas: C:\Program Files (x86)\Embarcadero\RAD Studio\9.0\bin\rtl160.bpl
Identificação do Relatório: dad7c33c-2a62-11e5-9afb-dc0ea1c9dbc2

**Comment by RRUZ** [comment]
Thanks for the info. Can you please attach the *Settings.ini* file located on this folder  %LOCALAPPDATA%\The Road To Delphi\DIC\XE2

**Comment by halyson** [comment]
[Global]
EnableDWMColorization=1
Enabled=1
FixIDEDisabledIconsDraw=1
AutogenerateColors=1
ThemeName=VS2012 Dark
ChangeIconsGutter=1
DockImages=transparent_light
DockGradientHor=0
DockCustom=1
DockCustomColors=0
DockStartGradActive=$00CC7A00
DockEndGradActive=$00CC7A00
DockStartGradInActive=$00CC7A00
DockEndGradInActive=$00CC7A00
HookSystemColors=1
ToolbarGradientHor=0
ToolbarCustomColors=0
ToolbarStartGrad=$00FF7F2A
ToolbarEndGrad=$00FFD42A
CheckUpdates=1
DockActiveFontColor=clWhite
DockInActiveFontColor=clWhite
DockActiveBorderColor=$00CC7A00
DockInActiveBorderColor=$00302D2D
DockBorderRounded=1
TabIDECustom=0
TabIDEOutLine=1
TabIDEStartGradActive=$00CC7A00
TabIDEEndGradActive=$00CC7A00
TabIDEStartGradInActive=$00302D2D
TabIDEEndGradInActive=$00302D2D
TabIDEActiveFontColor=clWhite
TabIDEInActiveFontColor=$002D2D2D
TabIDEOutLineColor=$00221F1F
HeaderCustom=0
HeaderStartGrad=$00696969
HeaderEndGrad=$00B4B4B4
HeaderFontColor=clBlack
HeaderBorderColor=$000F0F0F
VCLStyleName=
UseVCLStyles=1
VCLStylesForms=1
VCLStylesMenusColors=1
VCLStylesScrollBars=1
VCLStylesControls=1
MenuTransparent=0
MenuTransLevel=220
VirtualStringTreeFontDefault=1

**Comment by halyson** [comment]
It worked, I deleted the settings file and let the installation create a new one.

**Comment by RRUZ** [comment]
Perfect. Enjoy the plugin :)
