### ISSUE TITLE
Virus in downloaded Setup-Program

### ISSUE THREAD

**Issue by Twix291** [RRUZ/Delphi-IDE-Colorizer#28]
The pattern of 'HEUR/APC (Cloud) [HEUR/APC]'
detected in file 'C:\Users\User\Downloads\Setup_DIC.exe.
Action performed: Move file to quarantine

**Comment by RRUZ** [comment]
This a false postive check the virus total report for this file https://www.virustotal.com/es/file/4039590cfea07fe26a01843c660b308b343e1a1f3c468df8b98902fa04e1e46a/analysis/  Also you can check the source of the installer here https://github.com/RRUZ/Delphi-IDE-Colorizer/blob/master/IDE%20PlugIn/DIC_Install.nsi
