### ISSUE TITLE
Text color in the Structure pane and in the Project Manager?

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/Delphi-IDE-Colorizer#3]
In Delphi XE8, the text in the Structure pane and in the Project Manager has become Light Gray and therefore it is difficult to read:

![image](https://cloud.githubusercontent.com/assets/5140376/9147943/7b08b8d0-3d6f-11e5-9e92-1556bcefac37.png)

![image](https://cloud.githubusercontent.com/assets/5140376/9147950/9c0f48fa-3d6f-11e5-831e-f2bc79d4a887.png)

How can I turn it back to black color?

![image](https://cloud.githubusercontent.com/assets/5140376/9147978/469aa440-3d70-11e5-86f6-7008e4992193.png)

**Comment by RRUZ** [comment]
To change the color of the font, go to the settings window of the plugin. Select the *FontColor* Element, then  press the button *Save* and finally press the button *Apply*

![serttings](https://cloud.githubusercontent.com/assets/11446959/9152141/29c7a2b8-3df3-11e5-80e6-27208c258d81.png)

**Comment by PeterPanino** [comment]
Hi Rodrigo, many thanks, it worked.

However, it is strange that the text was gray although the "Delphi IDE Colorizer for RAD Studio" was UNchecked?

**Comment by RRUZ** [comment]
Hi this was a bug. I just uploaded a new version 0.7.9.4

**Comment by PeterPanino** [comment]
Hi, thank you very much!
    
    Sincerely,
    Peter
    
    Am 11.08.2015 um 03:55 schrieb Rodrigo
      Ruz:
    
    
      Hi this was a bug. I just uploaded a new version 0.7.9.4
      —
        Reply to this email directly or view
          it on GitHub.
