### ISSUE TITLE
Using DIC in different registry hives

### ISSUE THREAD

**Issue by tSlappy** [RRUZ/Delphi-IDE-Colorizer#32]
I am using Delphi mostly for writing IDE experts and I run Delphi in different registry hive (like bds.exe -pDelphi -rTestingHive). Is is possible to integrate DIC also for this hive? 

Currently I can choose which version to install (in installer) but this interates DIC into original Hive (hives are visible e.g. in Registry: 
![image](https://user-images.githubusercontent.com/1177940/29748477-f5b8a5de-8b17-11e7-9093-e750c4d55c05.png)

DITE already support this feature: 
![image](https://user-images.githubusercontent.com/1177940/29748494-3bad530a-8b18-11e7-9b7c-c7c46486bfae.png)

**Comment by RRUZ** [comment]
Hello, this is related to the [installer](https://github.com/RRUZ/Delphi-IDE-Colorizer/blob/master/IDE%20PlugIn/DIC_Install.nsi) ,  unfortunately I don't have much time on these days to work on that. 

 As workaround you can register manually the expert dll (DelphiIDEColorizer_XE8.dll).  
i.e for  XE8  and _TestingHive_ you must register the expert under this key. 

_Software\Embarcadero\TestingHive\16.0\Experts_

Let me know if the above works for you.

**Comment by tSlappy** [comment]
Works for me, thanks!
