### ISSUE TITLE
DIC coloring unnecessary components

### ISSUE THREAD

**Issue by tSlappy** [RRUZ/Delphi-IDE-Colorizer#33]
I am developing my own IDE expert. It adds few new docked windows to IDE, I am doing my own coloring of components using .Color .Font.Color properties.

TTreeView components placed on docked form have drawing issue: http://rad-installer.com/temp/forum/FindReferencesDI-coloring.wmv (3 MB)
(The white area is bad, when I disable DIC my drawing is performed correctly)

I tried to create my own component like **TColorTreeView = class(TTreeView)** to hide it from DIC, but this does not help.
How to disable drawing for single control (not whole TTreeView class - it is used in other windows which are drawn fine) ?

**Comment by tSlappy** [comment]
I found out when docking window is docked the coloring is applied because docked window parent form is TAppBuilder.

When I remove TAppBuilder from HookedWindows.dat file the coloring (of my docking window) is working correctly (but of course all controls from TAppBuilder are not colored).

Undocked window is fine because it's parent form is my class (TFindReferencesDockableForm).

**Comment by RRUZ** [comment]
Thanks for the report. and I'm glad you found the solution. sorry for not comment before but I'm really busy in these days.
