### ISSUE TITLE
Event Log dark theme cursor highlight unreadable

### ISSUE THREAD

**Issue by bdwilton** [RRUZ/Delphi-IDE-Colorizer#6]
Running DITE 0.8.1.6, Theme "VS2012 Dark".
Run any application to bring up the "Event Log" area.
Now select any line the cursor highlight is the same relative color as the text so become un-readable.
Same obviously if you highlight a few lines as well.

**Comment by RRUZ** [comment]
This issue was fixed, please check the new version (0.8.2.1)
