### ISSUE TITLE
Right Click on file name when your in open progect or file

### ISSUE THREAD

**Issue by parios59** [RRUZ/Delphi-IDE-Colorizer#9]
open ide
then open project
select project 
right click and menu is in some form of chinese,japanese or korean language.

I have screen shot.

**Comment by RRUZ** [comment]
Can you please attach the screenshot?

**Comment by parios59** [comment]
Yes

Please see attached file.

I just set the desktop to default and it corrected the problem, I could not set any profile without it affecting the right click menu.

If you need a shot instead of the pdf, let me know.

Thx

Pete Rios
El Toro Export, LLC
Dev./IS/IT Mgr.

Office (760) 352-4157
Fax (760) 352-5754
Cell (760) 455-9461
prios@eltoroexport.com<mailto:prios@eltoroexport.com>
parios59@gmail.com<mailto:parios59@gmail.com>

“Program to an interface, not in implementation!”
-Nick Hodges
P Please consider the environment before printing this e-mail
CONFIDENTIALITY NOTICE: This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message

**Comment by RRUZ** [comment]
It seems which  the attached file was not included.

**Comment by parios59** [comment]
[cid:image001.png@01D1152C.F1A2D5E0]

Pete Rios
El Toro Export, LLC
Dev./IS/IT Mgr.

Office (760) 352-4157
Fax (760) 352-5754
Cell (760) 455-9461
prios@eltoroexport.com<mailto:prios@eltoroexport.com>
parios59@gmail.com<mailto:parios59@gmail.com>

“Program to an interface, not in implementation!”
-Nick Hodges
P Please consider the environment before printing this e-mail
CONFIDENTIALITY NOTICE: This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message

**Comment by RRUZ** [comment]
This is seems the same issue reported [here](https://github.com/RRUZ/Delphi-IDE-Colorizer/issues/10). Try the new version 0.8.2.5

**Comment by parios59** [comment]
Great it works now
